title: blog.myitcv.io
author: Paul Jolly
email: paul@myitcv.io
description: >
  A largely Go-based blog
baseurl: ""
url: "https://blog.myitcv.io"
twitter_username: _myitcv
github_username:  myitcv
github: [metadata]

disqus:
  shortname: myitcv

theme: minima

markdown: redcarpet
redcarpet:
  extensions: ["footnotes","tables","with_toc_data"]

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

