title: blog.myitcv.io
author: Paul Jolly
email: paul@myitcv.io
description: >
  Thoughts on programming and engineering.
baseurl: ""
url: "http://blog.myitcv.io"
twitter_username: _myitcv
github_username:  myitcv
github: [metadata]

disqus:
  shortname: myitcv

theme: minima

markdown: redcarpet
redcarpet:
  extensions: [footnotes,tables]

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

