url: http://blog.myitcv.io
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
future: false
theme: minima
redcarpet:
  extensions: [footnotes,tables]

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

author: Paul Jolly
title: blog.myitcv.io
email: paul@myitcv.io
description: >
  Thoughts on programming and engineering.
baseurl: ""
url: "http://blog.myitcv.io"
twitter_username: _myitcv
github_username:  myitcv
