url: http://blog.myitcv.org.uk
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
future: false
redcarpet:
  extensions: [footnotes,tables]
authors:
  paul:
    display_name: Paul Jolly
    email: paul@myitcv.org.uk
    web: https://plus.google.com/105997489348527668257
    twitter: P__A__J
    github: myitcv
    blog: http://blog.myitcv.org.uk
