url: http://blog.myitcv.org.uk
markdown: rdiscount
pygments: true
safe: true
lsi: false
future: false
authors:
  paul:
    display_name: Paul Jolly
    email: paul@myitcv.org.uk
    web: https://plus.google.com/105997489348527668257
    twitter: P__A__J
    github: myitcv
    blog: http://blog.myitcv.org.uk
