url: http://blog.myitcv.io
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
future: false
redcarpet:
  extensions: [footnotes,tables]
authors:
  paul:
    display_name: Paul Jolly
    email: paul@myitcv.io
    web: https://plus.google.com/105997489348527668257
    twitter: _myitcv
    github: myitcv
    blog: http://blog.myitcv.io
